### ISSUE TITLE
Lägg till phone_number i pushar.

### ISSUE THREAD

**Issue by furedal** [swacedigital/infoping-backend#11]
För att se om jag behöver hantera meddelandet. Nu kommer det te.x stå "Du har fått ett nytt meddelande" när det är jag som skickade den.

**Comment by jsundstr** [comment]
phone_number är upptaget , identifierar om man står i just den gruppen och "nytt meddelande" ska ploppa upp för mottagaren (borde iof heta node_id men nu gör den inte det).
Så jag la till "sender" i pusharna som är sändarens telefonnummer (kan vara tom om ett api skickar) så kan du hantera "Du har fått ett nytt meddelande"
