### ISSUE TITLE
Lägg till route för att ta bort en grupp

### ISSUE THREAD

**Issue by furedal** [swacedigital/infoping-backend#20]
Borde inte spela någon roll om det är en toppgrupp eller inte

route: group_del_v3
params: org_key, node_id
return group { name, org_key, node_id etc...}

**Comment by jsundstr** [comment]
Nu finns det en route group_del_v3

Den raderar den gruppen samt alla undergrupper

Om man vill skicka upp ett varningsmeddelande innan man raderar gruppen så är det bra om man först kör en groups_get_v3
 med filter=del för att tala om hur många grupper som kommer att raderas

groups_get_v3
{
    "Q": {
         "token": "339E9828-09D7-4214-A855-D18D7A5FBC5F"
        ,"org_key": "3"
        ,"node_id": "ett.se"
        ,"filter":"del"
    }
}
{
  "A": {
    "status": "1",
    "filter": "del",
    "groups_count": "47",
    "groups": [
      {...



group_del_v3
{
    "Q": {
        "token": "339E9828-09D7-4214-A855-D18D7A5FBC5F"
        ,"org_key":"3"
        ,"node_id":"ett.se/Johan/Johan"
    }
}

{
  "A": {
    "status": "1",
    "filter": "del",
    "groups_count": "1",
    "groups": [
      {
        "org_key": "3",
        "node_id": "ett.se/Johan/Johan",
        "name": "Johan",
        "top_name": "ett.se",
        "is_private": "0",
        "premium": "1",
        "logo": "https://dev.infoping.se/rest2/ask/Q/logo/group/D3D4695F-466F-49D5-AF5D-495E21387342/t/339E9828-09D7-4214-A855-D18D7A5FBC5F/",
        "admins_count": "4",
        "members_count": "6",
        "receivers_count": "3",
        "last_update": "2016-05-20 15:26:40",
        "messages_count": "1",
        "no_answer_count": "0",
        "permissions": {
          "is_admin": "1",
          "is_sender": "1",
          "is_receiver": "1"
        }
      }
    ]
  }
}

**Comment by furedal** [comment]
Verkar funka
