### ISSUE TITLE
count för att se om det finns några members man kan välja i gruppen

### ISSUE THREAD

**Issue by furedal** [swacedigital/infoping-backend#21]
count för att se om det finns några members man kan välja i gruppen

swacedigital/infoping-android#11

**Comment by jsundstr** [comment]
nu finns det "sender_to_count" bredvid "groups_sender_count"
      "groups_sender_count": "4",
      "sender_to_count": "5",

**Comment by jsundstr** [comment]
Jag vet inte om du använder groups_sub_count till något men den visar antalet undergrupper till toppgruppen och borde kanske döpas om till just top_sub_groups_count eller liknande men törs inte göra det när allt börjar bli färdigt
