### ISSUE TITLE
Behörigheter på privata grupper är fishy

### ISSUE THREAD

**Issue by sbjorneh** [swacedigital/infoping-backend#6]
Problem med grupper på privata kontot:

Det går inte att lägga till medlemmar (den blir inte tillagd)
Det går inte att trycka på sparaknappen (inget händer)
Det går inte att bläddra mellan admin/medlemmar (man ser inte admin)

**Comment by jsundstr** [comment]
Ja inte den lättaste felbeskrivningen men jag har gått igenom alla fall som jag kan komma på och hittade ett fel när det gällde get users och det är åtgärdat i alla fall
