### ISSUE TITLE
admin_of, sender_to

### ISSUE THREAD

**Issue by furedal** [swacedigital/infoping-backend#8]
Gör jag request utan node_id och org_key så får jag felmeddelandet ”node_id not exists”.
Om jag tar med node_id och group_id så får jag istället ”no access to node”.

{"Q":{"token":"E439CF3D-E897-47ED-8F9D-369B8ADD5CE4","org_key":1992,"node_id":"kaffe","pageNum":1,"rowsPerPage":50,"searchStr":"","filter":"admin_of"}}

**Comment by jsundstr** [comment]
funkar nu
